name: Automated approval

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if:  "${{ (github.actor == 'developer-experience-bot[bot]') && contains(github.event.pull_request.labels.*.name, 'autorelease: snapshot') }}"
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - name: auto-approve
      id: auto-approve
      uses: coveo-platform/actions/auto-approve-action@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"