name: Automated approval

on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if:  "${{ (github.actor == 'developer-experience-bot[bot]') && contains(github.event.pull_request.labels.*.name, 'autorelease: snapshot') }}"
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
      with:
        egress-policy: audit

    - name: auto-approve
      id: auto-approve
      uses: coveo/actions/auto-approve-action@main
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"